# Question about 4c

In [1]:
random_binary_string(n = 12) = *([rand(['0','1']) for _ in 1:n]...)
random_hex_string(n=3) = *([rand(union('0':'9','A':'F')) for _ in 1:n]...);

In [6]:
some_example = random_binary_string()

"000001010011"

In [7]:
some_example

"000001010011"

$$
1 \times 2^0 + 1 \times 2^1 + 0 \times 2^2 + 0 \times 2^3 + 1 \times 2^4 + \ldots
$$

In [11]:
some_example[end] - '0' #this is a trick to convert from ascii character '0' or '1' to the numbers 0 or 1

1

In [14]:
function convert_character_to_number(c)
    if c == '0'
        return 0
    else #assume c == '1'
        return 1
    end  
#     return c - '0' #does the same as the above
end



convert_character_to_number (generic function with 1 method)

In [25]:
some_example = "1101" #13

"1101"

In [26]:
num_digits = length(some_example)

4

In [27]:
total = 0
for i in num_digits:-1:1
    digit_value = convert_character_to_number(some_example[i])
    power_value = num_digits-i
    actual_value = digit_value * 2^power_value
    total += actual_value
end
println(total)

13


In [18]:
for c in some_example 
    digit_value = convert_character_to_number(c)
    println(digit_value)
end

0
0
0
0
0
1
0
1
0
0
1
1


# Question 8

In [28]:
function array_table(array, heading)
    println(heading,":")
    for (i,a) in enumerate(array)
        println(i,"\t",a)
    end
end

names = [   "Amy Chan",
            "Maithili Mehta",
            "Anna Foeglein",
            "Andy Ferris",
            "Thomas Graham",
            "Elaine Schenk",
            "Jesse Woods",
            "Tina Moghaddam",
            "Paul Bellette",
            "Paul Vrbik",
            "Tom Cranitch",
            "Yoni Nazarathy",
            "Sam Hambleton",
            "Alistair Falconer",
            "Emma Comino",
            "Ivana Carrizo-Molina"]

sorted_names = sort(names)
array_table(sorted_names, "Sorted by first name")

println()

sorted_names = sort(names,by=(x)->reverse(split(x," ")))
array_table(sorted_names,"Sorted by last name")

Sorted by first name:
1	Alistair Falconer
2	Amy Chan
3	Andy Ferris
4	Anna Foeglein
5	Elaine Schenk
6	Emma Comino
7	Ivana Carrizo-Molina
8	Jesse Woods
9	Maithili Mehta
10	Paul Bellette
11	Paul Vrbik
12	Sam Hambleton
13	Thomas Graham
14	Tina Moghaddam
15	Tom Cranitch
16	Yoni Nazarathy

Sorted by last name:
1	Paul Bellette
2	Ivana Carrizo-Molina
3	Amy Chan
4	Emma Comino
5	Tom Cranitch
6	Alistair Falconer
7	Andy Ferris
8	Anna Foeglein
9	Thomas Graham
10	Sam Hambleton
11	Maithili Mehta
12	Tina Moghaddam
13	Yoni Nazarathy
14	Elaine Schenk
15	Paul Vrbik
16	Jesse Woods


In [29]:
? sort

search: sort sort! sortperm sortperm! sortslices sorted_names insorted Cshort



```
sort(v; alg::Algorithm=defalg(v), lt=isless, by=identity, rev::Bool=false, order::Ordering=Forward)
```

Variant of [`sort!`](@ref) that returns a sorted copy of `v` leaving `v` itself unmodified.

# Examples

```jldoctest
julia> v = [3, 1, 2];

julia> sort(v)
3-element Vector{Int64}:
 1
 2
 3

julia> v
3-element Vector{Int64}:
 3
 1
 2
```

---

```
sort(A; dims::Integer, alg::Algorithm=DEFAULT_UNSTABLE, lt=isless, by=identity, rev::Bool=false, order::Ordering=Forward)
```

Sort a multidimensional array `A` along the given dimension. See [`sort!`](@ref) for a description of possible keyword arguments.

To sort slices of an array, refer to [`sortslices`](@ref).

# Examples

```jldoctest
julia> A = [4 3; 1 2]
2×2 Matrix{Int64}:
 4  3
 1  2

julia> sort(A, dims = 1)
2×2 Matrix{Int64}:
 1  2
 4  3

julia> sort(A, dims = 2)
2×2 Matrix{Int64}:
 3  4
 1  2
```


In [30]:
function my_outer_function(x,f)
    return f(x) + f(x)
end

my_outer_function (generic function with 1 method)

In [32]:
abs(-352)

352

In [31]:
my_outer_function(-5,abs) #Lesson learned here is that we can pass functions as arguments....

10

Now instead of passing `abs` we create an anonymous function using `()->`

In [33]:
my_outer_function(-5,(z)->(z < 0 ? -z : z)) # using ? : (trinary operator)

10

In [34]:
sort([-3,5,-10])

3-element Vector{Int64}:
 -10
  -3
   5

In [35]:
sort([-3,5,-10],by = abs)

3-element Vector{Int64}:
  -3
   5
 -10

In [36]:
(x)->reverse(split(x," "))

#9 (generic function with 1 method)

In [37]:
split("hello guys how are you?"," ")

5-element Vector{SubString{String}}:
 "hello"
 "guys"
 "how"
 "are"
 "you?"

In [38]:
reverse(split("hello guys how are you?"," "))

5-element Vector{SubString{String}}:
 "you?"
 "are"
 "how"
 "guys"
 "hello"

In [39]:
reverse(split("Yoni Nazarathy"," "))

2-element Vector{SubString{String}}:
 "Nazarathy"
 "Yoni"

In [40]:
reverse(split("Yoni Nazarathy"," "))[1] #This is one way to take the last word of a sentence or name

"Nazarathy"

In [44]:
length(reverse(split("Yoni Nazarathy"," "))[1])

9

In [47]:
sort(names,by=(x)->length(reverse(split(x," "))[1]) )

16-element Vector{String}:
 "Amy Chan"
 "Maithili Mehta"
 "Jesse Woods"
 "Paul Vrbik"
 "Andy Ferris"
 "Thomas Graham"
 "Elaine Schenk"
 "Emma Comino"
 "Anna Foeglein"
 "Paul Bellette"
 "Tom Cranitch"
 "Alistair Falconer"
 "Tina Moghaddam"
 "Yoni Nazarathy"
 "Sam Hambleton"
 "Ivana Carrizo-Molina"

# License Plates

In [48]:
10^3 * 26^3

17576000

In [50]:
1-10^7/(10^3 * 26^3)

0.43104233045061446

# Bubble sort

In [51]:
function bubble_sort!(a)
    n = length(a)
    for i in 1:n-1
        for j in 1:n-i
            if a[j] > a[j+1]
                a[j], a[j+1] = a[j+1], a[j]
            end
        end
    end
    return a
end

bubble_sort! (generic function with 1 method)

In [52]:
data = [2,-3,5,10,20,15]
bubble_sort!(data)
data

6-element Vector{Int64}:
 -3
  2
  5
 10
 15
 20

In [53]:
data = ["Jack","Jill","Gemma","Janet"]
bubble_sort!(data)
data

4-element Vector{String}:
 "Gemma"
 "Jack"
 "Janet"
 "Jill"

In [56]:
"Jack" < "Janet"

true

In [57]:
function bubble_sort!(a;by=(u)->u) #BY DEFAULT IT HAS THE IDENTITY FUNCTION
    n = length(a)
    for i in 1:n-1
        for j in 1:n-i
            if by(a[j]) > by(a[j+1]) #THIS IS THE BUBBLE SORT UPGRADE TO USE by
                a[j], a[j+1] = a[j+1], a[j]
            end
        end
    end
    return a
end

bubble_sort! (generic function with 1 method)

In [58]:
data = ["Jack","Jill","Gemma","Janet"]
bubble_sort!(data)
data

4-element Vector{String}:
 "Gemma"
 "Jack"
 "Janet"
 "Jill"

In [59]:
reverse("hello")

"olleh"

In [61]:
data = ["Jack","Jill","Gemma","Janet"]
bubble_sort!(data,by=reverse)
data

4-element Vector{String}:
 "Gemma"
 "Jack"
 "Jill"
 "Janet"